#
# Copyright 2023 Canonical, Ltd.
#
import os
import shutil
import sys
from datetime import datetime
from urllib.request import urlopen

import yaml

VERSION = "v0.12.0"
SOURCE = (
    f"https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/{VERSION}/manifests"
)
FILES = [
    # "alertmanager-prometheusRule.yaml",
    "kubePrometheus-prometheusRule.yaml",
    "kubeStateMetrics-prometheusRule.yaml",
    "kubernetesControlPlane-prometheusRule.yaml",
    # "nodeExporter-prometheusRule.yaml",
    # "prometheus-prometheusRule.yaml",
    # "prometheusOperator-prometheusRule.yaml",
]
DIR = "src/prometheus_alert_rules"

shutil.rmtree(DIR, ignore_errors=True)
os.mkdir(DIR)

for file in FILES:
    source = f"{SOURCE}/{file}"
    data = [
        "---",
        f"# Automatically generated by {sys.argv}",
        f"# Source: {source}",
        f"# Timestamp: {datetime.utcnow().isoformat()}",
    ]
    contents = urlopen(source).read().decode().strip()
    parsed = yaml.safe_load(contents)
    data += [yaml.safe_dump(parsed["spec"])]

    with open(f"src/prometheus_alert_rules/{file}", "w") as fout:
        fout.write("\n".join(data))
