options:
  addons:
    description: |
      Space-separated list of addons that should be enabled and managed by the charm. Removing
      an addon from this list will disable it in the cluster.

      See https://microk8s.io/docs/addons for a comprehensive list of addons available in MicroK8s.

      Use "addon:arg1:arg2" to specify arguments when enabling a specific addon.

      Examples:
      - "dns rbac hostpath-storage ingress"
      - "dns rbac hostpath-storage ingress gpu:--version=v1.10.1"

    default: "dns rbac hostpath-storage ingress"
    type: string
  channel:
    description: |
      Specify MicroK8s version to install. This is the channel that will be passed to the "snap
      install microk8s" command. See also https://microk8s.io/docs/setting-snap-channel

      Examples:
      - ""                  # install latest version
      - "1.27/stable"       # install MicroK8s 1.27 from the stable branch
      - "1.27/edge"         # install MicroK8s 1.27 from the edge branch (getting all latest fixes)
      - "1.27-strict"       # install MicroK8s 1.27 with strict confinement
    default: ""
    type: string
  role:
    description: |
      Role for MicroK8s deployment, one of "", "control-plane" or "worker".

      Set the role to "control-plane" or "" to deploy all units as control plane nodes and form an
      HA control plane.

      Set the role to "worker" to deploy all units as workers. When deploying workers, the units
      will remain in waiting status until they are related to a microk8s control plane.

      The charm role cannot and must not be changed after deployment. Doing so will cause the units
      to go into error state until the change is reverted.
    default: ""
    type: string
  containerd_http_proxy:
    description: |
      Set an HTTP proxy to be used by containerd to pull images from image registries. This is
      useful when deploying the charm on a constrained environment.

      Example: "http://squid.internal:3128"
    default: ""
    type: string
  containerd_https_proxy:
    description: |
      Set an HTTPS proxy to be used by containerd to pull images from image registries. This is
      useful when deploying the charm on a constrained environment.

      Example: "http://squid.internal:3128"
    default: ""
    type: string
  containerd_no_proxy:
    description: |
      When configuring an HTTP/HTTPS proxy for containerd, specify the list of IP ranges to exclude.

      Example: "127.0.0.1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
    default: ""
    type: string
  automatic_certificate_reissue:
    description: |
      By default, MicroK8s will automatically regenerate server certificates when the IP address
      of the host machine changes. This is problematic in scenarios where a bridge is configured
      on the host and IP addresses on the bridge are changed frequently.

      Set this flag to false if that is the case to prevent MicroK8s from continuously restarting
      and affecting the service.

      This option is ignored and does not have any effect on multi-node clusters.
    default: true
    type: boolean
