##
## Copyright 2023 Canonical, Ltd.
##
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microk8s-observability
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microk8s-observability
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microk8s-observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microk8s-observability
subjects:
- kind: ServiceAccount
  name: microk8s-observability
  namespace: kube-system
